dataset:
    dataset_name: AwA2
    GZSL: True
    n_neighbors: 20
    data_path: /data/xingyu/Wasserstein_Autoencoders/data/AWA1
    save_path: /data/xingyu/gzsl_svae/experiments/AWA1
    
model:
    ifsample: False
    attr_size: 85
    input_size: 2048
    mid_size: 512
    hidden_size: 128
    classes: 50
train:
    start_epoch_classifier: 1
    epoch: 5
    generate_n_samples: 10
    classifier_epoch: 30
    learning_rate: 1e-4
    batch_size: 50
    check_point: 0
    interval: 200
    save_every: 1