dataset:
    dataset_name: FLO
    GZSL: True
    n_neighbors: 2
    data_path: /data/xingyu/Wasserstein_Autoencoders/data/FLO
    save_path: /data/xingyu/gzsl_svae/experiments/FLO
    
model:
    ifsample: False
    attr_size: 1024
    input_size: 2048
    mid_size: 512
    hidden_size: 64
    classes: 102
train:
    start_epoch_classifier: 5
    classifier_epoch: 200
    generate_n_samples: 20
    learning_rate: 1e-3
    batch_size: 128
    check_point: 0
    epoch: 1000
    interval: 100
    save_every: 20