dataset:
    dataset_name: 
    GZSL: True
    data_path: /data/xingyu/Wasserstein_Autoencoders/data/ImageNet
    save_path: /data/xingyu/gzsl_svae/experiments/imagenet
    
model:
    ifsample: False
    attr_size: 500
    input_size: 2048
    mid_size: 512
    hidden_size: 64
    classes: 1000
    unseen_classes: 500
train:
    epoch: 1000
    learning_rate: 1e-4
    batch_size: 128
    check_point: 0
    interval: 200
    save_every: 1